name: Daily Gemini

on:
  schedule:
    - cron: '0 0 * * *' # 毎日 0:00 UTC（JST 9:00）
  workflow_dispatch: # 手動実行も可能

jobs:
  ai-code-update:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリ取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 日付付きブランチ名を作成
      - name: Set branch name
        id: vars
        run: echo "branch=ai/code-update-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # 3. Gemini CLI 実行
      - name: Run Gemini CLI for code improvement
        id: gemini
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            競技プログラミングライブラリのドキュメント改善タスクを実行してください。

            **手順:**
            1. md/ ディレクトリから.mdファイルを1つ選択
            2. 対応するsrc/内の.hppファイルの実装を確認
            3. test/ ディレクトリ内の関連する.test.cppファイルも確認
            4. 以下の観点で評価・改善:

            **評価項目:**
            - **正確性**: コード例が実装と一致しているか
            - **完全性**: 重要な機能・制約が記載されているか
            - **可読性**: マークダウン構文が適切で、説明が分かりやすいか
            - **一貫性**: 他の.mdファイルと書式・構成が統一されているか

            **出力形式:**
            改善が必要な場合のみ、unified diff形式でパッチを出力してください。
            改善点がない場合は何も出力しないでください。

            **注意:**
            - 実装コードの動作を正確に理解してから文書化
            - 具体的な使用例やエッジケースも考慮
            - 数式や図表が必要な場合は適切に記述

      # 3.5. Gemini出力をファイルに保存
      - name: Save Gemini output to patch file
        run: |
          echo "${{ steps.gemini.outputs.response }}" > ai_update.patch

      # 4. パッチを適用
      - name: Apply AI patch
        run: |
          if [ -s ai_update.patch ]; then
            git apply ai_update.patch || echo "No applicable changes."
          else
            echo "No changes generated by AI."
          fi

      # 5. PR作成（毎回新しいブランチ）
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.vars.outputs.branch }}
          commit-message: "AI: Daily code improvement ($(date +'%Y-%m-%d'))"
          title: "AI: Daily code improvement ($(date +'%Y-%m-%d'))"
          body: |
            This PR was automatically generated by Gemini CLI.
            Please review and merge if appropriate.
          delete-branch: true
