name: AI Code Improvement PR (Daily New)

on:
  schedule:
    - cron: '0 0 * * *' # 毎日 0:00 UTC（JST 9:00）
  workflow_dispatch: # 手動実行も可能

jobs:
  ai-code-update:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリ取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 日付付きブランチ名を作成
      - name: Set branch name
        id: vars
        run: echo "branch=ai/code-update-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # 3. Gemini CLI 実行
      - name: Run Gemini CLI for code improvement
        uses: google-github-actions/run-gemini-cli@v1
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            まず md/ ディレクトリ内の.mdファイルを一つ好き適当に選んでください。
            そしてそのファイルに対応する src/ ディレクトリ内の .hpp ファイルを見てください。
            以下のことを確認してくだい。
            - 選んだ .md ファイルに書かれている内容に誤りがないか
            - 選んだ .md ファイルの内容に不足分がないか
            - 選んだ .md ファイルが読みやすいか
            必要があれば、他の .md ファイルや .hpp ファイルを参照・参考にして構いません。
            もし 選んだ .md に改善する余地があるならば、改善するパッチを unified diff 形式で出力してください。
          output_file: ./ai_update.patch

      # 4. パッチを適用
      - name: Apply AI patch
        run: |
          if [ -s ai_update.patch ]; then
            git apply ai_update.patch || echo "No applicable changes."
          else
            echo "No changes generated by AI."
          fi

      # 5. PR作成（毎回新しいブランチ）
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.vars.outputs.branch }}
          commit-message: "AI: Daily code improvement ($(date +'%Y-%m-%d'))"
          title: "AI: Daily code improvement ($(date +'%Y-%m-%d'))"
          body: |
            This PR was automatically generated by Gemini CLI.
            Please review and merge if appropriate.
          delete-branch: true
